### ISSUE TITLE
Documentary search crashes Exodus

### ISSUE THREAD

**Issue by The-NinthWave** [kodibae/repository.kodibae#10]
I have logged this under the Redux fork but it's not solved yet so I guess it would make BAE better if it was solved.

If one is trying to search in the "Documentaries" folder, Exoduspopulates a list of available categories. One can dig in the sub folder but once one chooses a documentary, as soon as Redux starts searching for providers, Kodi stops, not just Redux.

The same behavior is shown on ARM devices as well as Windows Kodi

I also tried on an ARM device running CoreELEC where Kodi is the system as opposed to be running on Android and, when I started a search in "documentaries", it hung the box to a point I had to disconnect it and wait 15 seconds before plugging it again for it to reboot correctly.

**Comment by dobbelina** [comment]
https://github.com/kodibae/repository.kodibae/issues/8

**Comment by jbakker81** [comment]
> Issue raised and closed here: #8

How is this issue closed?
The issue in #8 still exists for me and others.

**Comment by wozney** [comment]
Same question as @jbakker81.

#8 only closed the issue and did not fix anything because we all still have the same problem

**Comment by kodibae** [comment]
fixed yalla 💯

**Comment by The-NinthWave** [comment]
> 
> 
> fixed yalla 💯

Does it mean like "fixe voilà" ?

I tried and it is not solved.

**Comment by dobbelina** [comment]
Yalla it's still broken..

**Comment by wozney** [comment]
It will probably be pushed LIVE when they do the next update. Do they have nightly releases. The update could be in there if you need it asap, other then the nightly probably have to wait for the next update.

On Oct. 16, 2019 4:24 p.m., dobbelina <notifications@github.com> wrote:

Yalla it's still broken..
